name: Build and Publish Docker Image
on:
  push:
    branches:
      - '**'
    tags:
      - "v*"
jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    strategy:
      matrix:
        app: [admin-server, api-server, auth-server, image-server]
    name: '[${{ matrix.app }}] Build & push Docker'
    runs-on: ubuntu-latest
    env:
      IMAGE: '${{ github.repository_owner }}/${{ matrix.app }}'
      APP: ${{ matrix.app }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE }}
          tags: |
            # branch event
            type=ref,event=branch,suffix=-{{sha}}
            # tag event
            type=ref,event=tag

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 'ghcr.io/${{ steps.meta.outputs.tags }}'
          build-args: |
            APP=${{ matrix.app }}

      # Comment build info in commit
      - uses: actions/github-script@0.9.0
        env:
          STDOUT: "[${{ matrix.app }}] new image: `${{ fromJson(steps.docker_build.outputs.metadata)['image.name'] }}` version: `${{ steps.meta.outputs.version }}` @ ${{ steps.meta.outputs.tags }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: process.env.STDOUT
            })

      - name: Image digest
        run: echo "${{ steps.docker_build.outputs.metadata }}"
